### PR TITLE
Load balancer fixes, Terraform readability changes.

### LINKED ISSUE #961: Provisioner: Break up the monolith aws/main.tf into more easily ingestible bites

### PR DESCRIPTION
**Pull request by emmetthitz**
Fixes #961, #934 
- Breaks up the related terraform config components into their related categories
- Fixes load balancer health checks to bring them online more quickly

### CODE REVIEW

File: pkg/provision/aws_types.go [hunk 1]
```diff
@@ -11,9 +11,10 @@ type AWS struct {
 type AWSTerraformData struct {
 	Version           string `json:"version"`
 	Region            string `json:"region,omitempty"`
+	AvailabilityZone  string `json:"AZ,omitempty"`
 	PrivateSSHKeyPath string `json:"private_ssh_key_path"`
 	PublicSSHKeyPath  string `json:"public_ssh_key_path"`
-	SSHUser           string `json:"ssh_user,omitempty"`
+	SSHUser           string `json:"ssh_user"`
```
Comment (dkoshkin) [inline pkg/provision/aws_types.go]: Can this ever be empty?

File: terraform/providers/aws/elb.tf [hunk 2]
```diff
@@ -0,0 +1,95 @@
+resource "aws_s3_bucket" "lb_logs" {
+  count  = 0
+  //"${var.master_count > 1 || var.ingress_count > 1 ? 1 : 0}"
```
Comment (dkoshkin) [inline terraform/providers/aws/elb.tf]: This conditional can be removed now.

File: terraform/providers/aws/instances.tf [hunk 3]
```diff
@@ -0,0 +1,203 @@
+resource "aws_instance" "bastion" {
```
Comment (dkoshkin) [inline terraform/providers/aws/instances.tf]: Is the bastion being used? I think we wanted to hold off on this until we figure some more things out?

Comment (emmetthitz) [reply terraform/providers/aws/instances.tf]: Yeah. The count is set to 0. I left todos where stuff will need to be changed, otherwise this isn't actually doing anything.

File: terraform/providers/aws/elb.tf (hunk 2 above)
Comment (emmetthitz) [reply terraform/providers/aws/elb.tf]: 👍

**Comment by alexbrand** [comment]
The tests are failing because the load balancers take a while to come up (I have seen them take ~3 minutes). We will have to bump up the daemon integration test timeout... probably something like 5 minutes.

**Comment by emmetthitz** [comment]
Oh bless. I was slowly going crazy because I couldn't reproduce what was happening with the tests manually.

File: pkg/provision/aws_types.go (hunk 1 above)
Comment (emmetthitz) [reply pkg/provision/aws_types.go]: I.e. no user is specified in the plan, so the tfvar doesn't get marshalled. No tfvar for that field defaults to root. 

Instead, always marshalling the tfvar causes it to be empty string in the case where it's not set in the plan, which causes failure down the pipe (here).

File: pkg/provision/aws.go [hunk 4]
```diff
@@ -165,8 +161,6 @@ func (aws *AWS) buildPopulatedPlan(plan install.Plan) (*install.Plan, error) {
 		plan.Storage = install.OptionalNodeGroup(nodeGroupFromSlices(tfNodes.IPs, tfNodes.InternalIPs, tfNodes.Hosts))
 	}
 
-	// SSH
-	plan.Cluster.SSH.User = "ubuntu"
```
Comment (emmetthitz) [inline pkg/provision/aws.go]: This needs to be set before the TFVars get marshalled. This line of code wasn't actually doing anything useful.

File: terraform/providers/aws/variables.tf [hunk 5]
```diff
@@ -20,7 +24,7 @@ variable "public_ssh_key_path" {
 }
 
 variable "ssh_user" {
-  default = "ubuntu"
+  default = ""
```
Comment (emmetthitz) [inline terraform/providers/aws/variables.tf]: pkg/provision/aws.go:169 was being caught by this.

Comment (alexbrand) [reply terraform/providers/aws/variables.tf]: This is exactly why I wanted us to have no defaults in this file.

Comment (emmetthitz) [reply terraform/providers/aws/variables.tf]: Alex "Confucius" Brand at it again.
