### PR TITLE
Fix dashboard when generating plan file

### LINKED ISSUE #727: Duplicate "dashboard" flag in 1.5.1 kismatic-cluster.yaml
After downloading kismatic v.1.5.1 and executing `./kismatic install plan` the follow is shown in the plan file.

```
dashboard: null
dashbard: null
```

### PR DESCRIPTION
**Pull request by alexbrand**
Fixes #727

### CODE REVIEW

File: pkg/install/plan.go [hunk 1]
```diff
@@ -155,7 +155,10 @@ var yamlKeyRE = regexp.MustCompile(`[^a-zA-Z]*([a-z_\-A-Z]+)[ ]*:`)
 
 // Write the plan to the file system
 func (fp *FilePlanner) Write(p *Plan) error {
-	oneTimeComments := commentMap
+	oneTimeComments := map[string]string{}
```
Comment (dkoshkin) [inline pkg/install/plan.go]: What was the reason to do this?

Comment (alexbrand) [inline pkg/install/plan.go]: The new unit test surfaced a bug. The original intent here was to create a copy of comment map because we delete keys from it, but we were only making a copy of the reference to the map, and not the map itself.

With this change, we create a copy of the comment map.

**Comment by dkoshkin** [comment]
LGTM. The new test should prevent these kind of bugs in the future.
